import {chromium,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdir} from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {blank,record} from '../src/model.js';
import {exportField,sha256,decodeField,unpack} from '../src/packets.js';
const root=path.resolve(import.meta.dirname,'..'),origin='http://127.0.0.1:4182';
const server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:root,env:{...process.env,SCOUT_PORT:'4182'},stdio:['ignore','pipe','inherit'],windowsHide:true});
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});let browser;
try{
 browser=await chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:process.env.SCOUT_BROWSER_PATH||path.join(process.env.LOCALAPPDATA,'ms-playwright/chromium-1223/chrome-win64/chrome.exe')}:{})});
 const context=await browser.newContext({viewport:{width:390,height:844},locale:'en-GB',serviceWorkers:'block',acceptDownloads:true});
 await context.route('**/*',route=>route.request().url().startsWith(origin)?route.continue():route.abort());
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);await expect(page.locator('[data-action=new-trip]')).toBeVisible();
 const state=blank();
 for(const id of ['A','B']){state.records.push(record('trip',{name:'Trip '+id,city:'Test city',timezone:'Asia/Hong_Kong',template:'blank'},'phone',id));state.records.push(record('set',{tripId:id,name:'Stop '+id,code:'S-'+id,notes:'Field notes',camera:{name:'Sony'},startedAt:'2026-10-03T00:00:00.000Z',endedAt:'2026-10-03T01:00:00.000Z',timezone:'Asia/Hong_Kong'},'phone','s'+id));}
 for(const [id,tripId,blobId,deleted]of [['a1','A','shared',false],['a2','A','unique',false],['a3','A','archived',true],['b1','B','shared',false]])state.records.push(record('asset',{tripId,setId:'s'+tripId,fileName:id+'.jpg',source:'field',blobId,notes:'test',deleted},'phone',id));
 state.records.push(record('reading',{tripId:'A',setId:'sA',label:'Sun',method:'manual_ev',value:10,instrument:'manual',protocol:'test',calibration:'uncalibrated',measuredAt:'2026-10-03T00:00:00.000Z'},'phone','reading'));
 const png=await sharp({create:{width:30,height:20,channels:3,background:'#556644'}}).jpeg().toBuffer();
 const blobs=await Promise.all(['shared','unique','original','archived','orphan'].map(async id=>({id,blob:new Blob([png],{type:'image/jpeg'}),sha256:await sha256(png)})));
 state.records.find(r=>r.id==='a2').originals=[{blobId:'original',fileName:'a2-original.jpg',mime:'image/jpeg',size:png.length,sha256:await sha256(png)}];
 const oldBackup=await exportField({state,blobs,local:{}},'A');
 await page.evaluate(async({state,blobs})=>{const db=await new Promise(resolve=>{const q=indexedDB.open('scout-v2');q.onsuccess=()=>resolve(q.result);});await new Promise((resolve,reject)=>{const tx=db.transaction(['state','blobs','local'],'readwrite');tx.objectStore('state').put(state,'main');for(const b of blobs)tx.objectStore('blobs').put({...b,blob:new Blob([new Uint8Array(b.bytes)],{type:'image/jpeg'})});tx.objectStore('local').put({device:{id:'phone',name:'Test phone'},activeTrip:'A',language:'en',legacyMigrated:true,onlineWeather:false,nextDestination:{tripId:'A',recordId:'sA',name:'Stop A'}},'preferences');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();},{state,blobs:blobs.map(b=>({id:b.id,sha256:b.sha256,bytes:[...png]}))});
 const read=()=>page.evaluate(async()=>{const db=await new Promise(resolve=>{const q=indexedDB.open('scout-v2');q.onsuccess=()=>resolve(q.result);});return await new Promise(resolve=>{const tx=db.transaction(['state','local','blobs']),s=tx.objectStore('state').get('main'),l=tx.objectStore('local').get('preferences'),b=tx.objectStore('blobs').getAllKeys();tx.oncomplete=()=>{db.close();resolve({state:s.result,local:l.result,blobs:b.result});};});});
 await page.reload();await page.locator('[data-action=nav][data-id=library]').click();
 await page.locator('[data-action=asset][data-id=a2]').click();await page.locator('#modal [data-action=purge]').click();await expect(page.locator('[data-action=confirm-cleanup]')).toBeDisabled();await expect(page.locator('#modal')).toContainText('Stored files: 2');await page.locator('#modal [data-action=close]').click();expect((await read()).blobs).toHaveLength(5);
 await page.locator('[data-action=select-images]').click();await expect(page.locator('.selection-bar')).toContainText('Selected images: 2');await page.locator('#search').fill('a2');await expect(page.locator('.selection-bar')).toContainText('Selected images: 0');await page.locator('[data-action=select-images]').click();await page.locator('[data-action=trash-assets]').click();await page.locator('[data-action=workspace-filter][data-id=trash]').click();await page.locator('#search').fill('a2');await page.locator('[data-action=select-images]').click();await page.locator('[data-action=purge-images]').click();await expect(page.locator('.cleanup-counts')).toContainText('Images: 1');
 // Changing the notebook while a preview is open must demand a fresh review.
 await page.evaluate(async()=>{const db=await new Promise(resolve=>{const q=indexedDB.open('scout-v2');q.onsuccess=()=>resolve(q.result);});await new Promise(resolve=>{const tx=db.transaction('state','readwrite'),store=tx.objectStore('state'),q=store.get('main');q.onsuccess=()=>{const s=q.result;s.generation++;store.put(s,'main');};tx.oncomplete=resolve;});db.close();});
 await page.locator('#cleanup-ack').check();await page.locator('[data-action=confirm-cleanup]').click();await expect(page.locator('#cleanup-ack')).not.toBeChecked();expect((await read()).blobs).toHaveLength(5);
 await page.locator('#cleanup-ack').check();await page.locator('[data-action=confirm-cleanup]').click();await expect(page.locator('#modal')).not.toBeVisible();let data=await read();expect(data.blobs).toEqual(['archived','orphan','shared']);expect(data.state.records.find(r=>r.id==='a2').purgedAt).toBeTruthy();
 await page.locator('[data-action=workspace-filter][data-id=all]').click();await page.locator('#search').fill('');await page.locator('[data-action=asset][data-id=a1]').click();await page.locator('#modal [data-action=purge]').click();await expect(page.locator('#modal')).toContainText('Shared files kept: 1');await page.locator('#cleanup-ack').check();await page.locator('[data-action=confirm-cleanup]').click();expect((await read()).blobs).toContain('shared');
 await page.locator('[data-action=nav][data-id=settings]').click();await page.locator('[data-action=purge][data-id=A]').click();await expect(page.locator('.cleanup-counts')).toContainText('Images: 1');await expect(page.locator('.cleanup-counts')).toContainText('Light readings: 1');
 await mkdir(path.join(root,'test-results'),{recursive:true});
 for(const [width,height]of [[390,844],[360,640],[320,568],[844,390]]){await page.setViewportSize({width,height});for(const expanded of [false,true]){await page.locator('.cleanup-scroll details').evaluate((el,open)=>el.open=open,expanded);for(const button of await page.locator('.cleanup-footer button').all()){const box=await button.boundingBox();expect(box.height).toBeGreaterThanOrEqual(44);expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width+1);expect(box.y+box.height).toBeLessThanOrEqual(height+1);expect(await button.evaluate(el=>{const r=el.getBoundingClientRect();return el.contains(document.elementFromPoint(r.x+r.width/2,r.y+r.height/2));})).toBe(true);}}}
 await page.setViewportSize({width:390,height:844});await page.locator('#modal [data-action=close]').click();await page.locator('#language').selectOption('zh');await page.locator('[data-action=purge][data-id=A]').click();await expect(page.locator('#modal')).toContainText('删除行程');await expect(page.locator('#modal')).toContainText('我了解这会永久移除 Scout 中的副本');await page.screenshot({path:path.join(root,'test-results/cleanup-chinese.png')});
 await page.locator('#cleanup-ack').check();await page.locator('[data-action=confirm-cleanup]').click();await expect(page.locator('#modal')).not.toBeVisible();data=await read();expect(data.local.activeTrip).toBe('B');expect(data.local.nextDestination).toBeUndefined();expect(data.blobs).toEqual(['orphan','shared']);
 await page.locator('#language').selectOption('en');await page.locator('[data-action=purge-unused]').click();await expect(page.locator('#modal')).toContainText('Stored files: 1');await page.locator('#cleanup-ack').check();await page.locator('[data-action=confirm-cleanup]').click();await expect(page.locator('#modal')).not.toBeVisible();expect((await read()).blobs).toEqual(['shared']);
 await page.locator('[data-action=nav][data-id=transfer]').click();await page.locator('#import-file').setInputFiles({name:'old-backup.zip',mimeType:'application/zip',buffer:Buffer.from(oldBackup.bytes)});await page.locator('[data-action=apply-import]').click();await expect(page.locator('#modal')).not.toBeVisible();expect((await read()).blobs).toEqual(['shared']);
 await page.getByText('Deleted trips · 1',{exact:true}).click();const downloadEvent=page.waitForEvent('download');await page.locator('[data-action=deletion-export]').click();const download=await downloadEvent;const {readFile}=await import('node:fs/promises');const restored=await decodeField(unpack(new Uint8Array(await readFile(await download.path()))));expect(restored.blobs).toHaveLength(0);expect(restored.packet.records.every(r=>r.purgedAt)).toBe(true);

 const receiving=await browser.newContext({serviceWorkers:'block',locale:'en-GB'}),other=await receiving.newPage();other.on('pageerror',e=>errors.push(e.message));await other.goto(origin);await expect(other.locator('[data-action=new-trip]')).toBeVisible();await other.locator('[data-action=nav][data-id=transfer]').click();await other.locator('#import-file').setInputFiles({name:'restore.zip',mimeType:'application/zip',buffer:Buffer.from(oldBackup.bytes)});await other.locator('[data-action=apply-import]').click();await expect(other.locator('#modal')).not.toBeVisible();
 await other.locator('#import-file').setInputFiles({name:'delete.zip',mimeType:'application/zip',buffer:await readFile(await download.path())});await expect(other.locator('#modal')).toContainText('Permanent deletions in this package');await expect(other.locator('[data-action=apply-import]')).toBeDisabled();await other.locator('#import-delete-ack').check();await other.locator('[data-action=apply-import]').click();await expect(other.locator('#modal')).not.toBeVisible();await other.locator('[data-action=nav][data-id=field]').click();await expect(other.locator('[data-action=quick-start]')).toBeVisible();await receiving.close();
 await page.locator('[data-action=nav][data-id=settings]').click();await page.locator('[data-action=purge][data-id=B]').click();await page.locator('#cleanup-ack').check();await page.locator('[data-action=confirm-cleanup]').click();await expect(page.locator('#modal')).not.toBeVisible();await page.locator('[data-action=nav][data-id=field]').click();await expect(page.locator('[data-action=quick-start]')).toBeVisible();await page.reload();await expect(page.locator('[data-action=quick-start]')).toBeVisible();data=await read();expect(data.local.activeTrip).toBeNull();expect(data.blobs).toEqual([]);expect(errors).toEqual([]);
 console.log('Cleanup: single/bulk cancel and confirm, original bytes freed, shared files retained, concurrent-change re-review, trip cascade, bilingual mobile footer, orphan cleanup, stale import, deletion export and last-trip reload passed.');
}finally{await browser?.close();server.kill();}
