import {chromium,expect} from '@playwright/test';
import {spawn} from 'node:child_process';
import {mkdir,readFile} from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';
import {zipSync,strToU8} from 'fflate';
import {blank,record} from '../src/model.js';
import {exportField,sha256,decodeField,unpack} from '../src/packets.js';
const root=path.resolve(import.meta.dirname,'..'),origin='http://127.0.0.1:4183';
const server=spawn(process.execPath,['scripts/serve.mjs'],{cwd:root,env:{...process.env,SCOUT_PORT:'4183'},stdio:['ignore','pipe','inherit'],windowsHide:true});
await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);});let browser;
try{
 browser=await chromium.launch({headless:true,...(process.platform==='win32'?{executablePath:process.env.SCOUT_BROWSER_PATH||path.join(process.env.LOCALAPPDATA,'ms-playwright/chromium-1223/chrome-win64/chrome.exe')}:{})});
 const context=await browser.newContext({viewport:{width:1440,height:1000},locale:'en-GB',serviceWorkers:'block',acceptDownloads:true});
 await context.route('**/*',r=>r.request().url().startsWith(origin)?r.continue():r.abort());
 const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin);await expect(page.getByText('Bring your shoot together.',{exact:true})).toBeVisible();
 const state=blank(),blobs=[];
 state.records.push(record('trip',{name:'Hong Kong · Field study',city:'Hong Kong',timezone:'Asia/Hong_Kong',template:'blank'},'phone','trip'));
 for(const [id,name]of [['s1','Sham Shui Po · market'],['s2','West Kowloon · waterfront']])state.records.push(record('set',{tripId:'trip',code:id==='s1'?'HK-021':'HK-022',name,notes:'Warm shop light under cool street shadows.',camera:{name:'ILCE-7CR'},location:{lat:22.3302,lng:114.1621,accuracy:12},startedAt:'2026-10-03T09:00:00.000Z',endedAt:'2026-10-03T10:00:00.000Z',timezone:'Asia/Hong_Kong'},'phone',id));
 state.records.push(record('reading',{tripId:'trip',setId:'s1',label:'Street shade',method:'manual_ev',value:8.3,instrument:'Test meter',protocol:'Fixture',calibration:'Uncalibrated fixture',measuredAt:'2026-10-03T09:05:00.000Z'},'phone','reading'));
 let image;
 for(let i=0;i<6;i++){
  const svg=`<svg width="720" height="480" xmlns="http://www.w3.org/2000/svg"><rect width="720" height="480" fill="${['#687975','#8d8876','#98936e','#435764','#747f76','#797564'][i]}"/><path d="M0 350L200 120L340 300L470 80L720 320V480H0" fill="#263e3b"/><path d="M280 480L400 170L520 480" fill="#b69e72"/><rect x="80" y="210" width="70" height="125" fill="#ccae6c"/></svg>`;
  image=await sharp(Buffer.from(svg)).jpeg().toBuffer();const id='preview'+i;blobs.push({id,blob:new Blob([image],{type:'image/jpeg'}),sha256:await sha256(image)});
  state.records.push(record('asset',{tripId:'trip',setId:i<4?'s1':null,fileName:i<2?'Phone-vibe-0'+i+'.jpg':'DSC00'+i+'.ARW',source:i<2?'field':'camera',camera:i<2?'Samsung S25 Edge':i===5?'X-T5':'ILCE-7CR',role:i<2?'vibe':'detail',notes:'',blobId:id},'phone','a'+i));
 }
 const packet=await exportField({state,blobs,local:{}},'trip');await page.locator('#import-file').setInputFiles({name:'phone.zip',mimeType:'application/zip',buffer:Buffer.from(packet.bytes)});await page.locator('[data-action=apply-import]').click();await expect(page.locator('.file-tile')).toHaveCount(6);
 const read=()=>page.evaluate(async()=>{const db=await new Promise(resolve=>{const q=indexedDB.open('scout-v2');q.onsuccess=()=>resolve(q.result);});return await new Promise(resolve=>{const tx=db.transaction(['state','blobs']),s=tx.objectStore('state').get('main'),b=tx.objectStore('blobs').getAllKeys();tx.oncomplete=()=>{db.close();resolve({state:s.result,blobs:b.result});};});});
 await page.locator('[data-action=select-asset][data-id=a0]').click();await page.locator('[data-action=select-asset][data-id=a3]').click({modifiers:['Shift']});await expect(page.locator('.selection-bar')).toContainText('Selected images: 4');
 await page.locator('#batch-role').selectOption('environment');await page.locator('[data-action=batch-role]').click();expect((await read()).state.records.filter(a=>a.role==='environment')).toHaveLength(4);
 await page.locator('[data-action=workspace-filter][data-id=phone]').click();await expect(page.locator('.file-tile')).toHaveCount(2);await page.locator('[data-action=select-images]').click();await page.locator('#batch-stop').selectOption('s2');await page.locator('[data-action=batch-assign]').click();expect((await read()).state.records.filter(a=>a.kind==='asset'&&a.setId==='s2')).toHaveLength(2);
 await page.locator('[data-action=select-images]').click();await page.locator('[data-action=trash-assets]').click();await expect(page.locator('.file-tile')).toHaveCount(0);expect((await read()).blobs).toHaveLength(6);await page.locator('[data-action=undo-trash]').click();await expect(page.locator('.file-tile')).toHaveCount(2);
 await page.locator('[data-action=select-images]').click();await page.locator('[data-action=trash-assets]').click();await page.reload();await page.locator('[data-action=workspace-filter][data-id=trash]').click();await expect(page.locator('.file-tile')).toHaveCount(2);await page.locator('[data-action=select-images]').click();await page.locator('[data-action=restore-assets]').click();await expect(page.locator('.file-tile')).toHaveCount(0);
 await page.locator('[data-action=workspace-filter][data-id=all]').click();await page.locator('#search').fill('X-T5');await expect(page.locator('.file-tile')).toHaveCount(1);await page.locator('#search').press('Control+a');await expect(page.locator('.selection-bar')).toContainText('Selected images: 0');await page.locator('#search').fill('');await page.locator('#search').blur();await page.locator('body').click({position:{x:8,y:200}});await page.keyboard.press('Control+a');await expect(page.locator('.selection-bar')).toContainText('Selected images: 6');await page.locator('[data-action=clear-images]').click();
 // Direct file input exercises real EXIF extraction, exact byte identity and duplicates.
 const jpeg=await sharp({create:{width:64,height:40,channels:3,background:'#52685b'}}).withExif({IFD0:{Make:'SONY',Model:'ILCE-7CR'},IFD2:{DateTimeOriginal:'2026:10:03 17:15:23'}}).jpeg().toBuffer();const hash=await sha256(jpeg);
 const raw=Buffer.from('Unsupported RAW fixture, not a photograph'),rawHash=await sha256(raw);
 await page.locator('#camera-files').setInputFiles([{name:'New-camera.jpg',mimeType:'image/jpeg',buffer:jpeg},{name:'Copy.jpg',mimeType:'image/jpeg',buffer:jpeg},{name:'No-preview.ARW',mimeType:'application/octet-stream',buffer:raw}]);await expect(page.getByRole('heading',{name:'Review camera import',exact:true})).toBeVisible();await expect(page.locator('#modal')).toContainText('2 new files · 1 duplicates');await page.locator('[data-action=apply-import]').click();await expect(page.locator('.file-tile')).toHaveCount(8);
 let data=await read(),imported=data.state.records.find(a=>a.sha256===hash);expect(imported.camera).toBe('ILCE-7CR');expect(imported.captureWall).toBe('2026-10-03T17:15:23');expect(imported.setId).toBeNull();expect(imported.originals).toBeUndefined();expect(data.state.records.find(a=>a.sha256===rawHash).blobId).toBeNull();
 // The richer CLI catalogue can supply the missing preview without losing user edits.
 const rawId='camera-trip-'+rawHash;await page.locator(`[data-action=asset][data-id="${rawId}"]`).click();await page.locator('#asset-form [name=role]').selectOption('lighting');await page.locator('#asset-form [name=setId]').selectOption('s1');await page.locator('#asset-form [type=submit]').click();await expect(page.locator('#modal')).not.toBeVisible();
 const cat={format:'scout-camera',schemaVersion:1,assets:[{fileName:'No-preview.ARW',originalRelativePath:'Sony/No-preview.ARW',sha256:rawHash,previewPath:'preview.jpg',previewSha256:await sha256(image),captureWall:'2026-10-03T17:15:24',camera:'ILCE-7CR',exif:{Model:'ILCE-7CR'},warnings:[]}]};
 await page.locator('#import-file').setInputFiles({name:'catalogue.zip',mimeType:'application/zip',buffer:Buffer.from(zipSync({'catalogue.json':strToU8(JSON.stringify(cat)),'preview.jpg':image}))});await page.locator('[data-action=apply-import]').click();data=await read();const enriched=data.state.records.find(a=>a.id===rawId);expect(enriched.role).toBe('lighting');expect(enriched.setId).toBe('s1');expect(enriched.blobId).toBeTruthy();
 await page.locator('[data-action=review-asset][data-id=a2]').click();await expect(page.locator('.scene-inspector')).toContainText('8.3 EV100');await expect(page.locator('.scene-inspector')).toContainText('22.33020, 114.16210');
 await mkdir(path.join(root,'test-results'),{recursive:true});await page.screenshot({path:path.join(root,'test-results/workspace-desktop.png'),fullPage:true});
 await page.locator('#language').selectOption('zh');await expect(page.locator('[data-action=workspace-filter][data-id=trash]')).toContainText('项目回收站');await page.screenshot({path:path.join(root,'test-results/workspace-chinese.png'),fullPage:true});
 await page.locator('[data-action=close-review]').click();await page.locator('[data-action=select-images]').click();
 for(const [width,height]of [[390,844],[320,568],[844,390],[1440,1000]]){await page.setViewportSize({width,height});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);const dock=page.locator('.batch-dock');await dock.scrollIntoViewIfNeeded();for(const button of await dock.locator('button').all()){const box=await button.boundingBox();expect(box.height).toBeGreaterThanOrEqual(44);expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(width+1);}}
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(root,'test-results/workspace-phone-files.png'),fullPage:true});
 await page.locator('#language').selectOption('en');await page.locator('#nav [data-id=field]').click();await page.locator('[data-action=open][data-id=s1]').click();await expect(page.locator('#place-details')).not.toHaveAttribute('open','');await page.screenshot({path:path.join(root,'test-results/field-guide-phone.png'),fullPage:true});
 await page.locator('#nav [data-id=transfer]').click();const downloading=page.waitForEvent('download');await page.locator('[data-action=export][data-id=backup]').click();const download=await downloading;const restored=await decodeField(unpack(new Uint8Array(await readFile(await download.path()))));expect(restored.packet.records.find(a=>a.id===rawId).role).toBe('lighting');expect(restored.packet.records.find(a=>a.sha256===hash).captureWall).toBe('2026-10-03T17:15:23');expect(errors).toEqual([]);
 console.log('Workspace: upgrade import, range/keyboard selection, batch roles/assignment, reversible Trash, reload/restore, EXIF import/duplicates/RAW fallback, catalogue enrichment, scene inspector, bilingual responsive layout and export passed.');
}finally{await browser?.close();server.kill();}
