import QRCode from 'qrcode';
import {strFromU8} from 'fflate';
import {Store} from './store.js';
import {uid,now,record,revise,put,get,active,merge,resolve,migrateLegacy,timezoneValid,localTime,ev100,shutterSeconds,comparable,suggest,validateRecords} from './model.js';
import {exportTrip,decodeField,unpack,sha256,escapeHTML as e,MAX_PACKAGE} from './packets.js';
import {native,measureLight,stopMeter,locate,deliver} from './native.js';
import {daylight} from './sun.js';
import {places,days} from './hk-template.js';

const $=s=>document.querySelector(s), app=$('#app'),modal=$('#modal');
const store=new Store();let formSave=Promise.resolve(),updateReady=false,editVersion=0,formDirty=false,pendingExports=[];let snapshot,state,local,view='field',selected=null,urls=new Map(),pendingImport=null,sample=null,saving=0,search='',toastTimer;
const roles=['unclassified','identification','environment','material','lighting','gray reference','bracket','panorama','detail','signage'];
const fmt=n=>Number.isFinite(n)?Number(n.toFixed(2)).toLocaleString():'—';
const button=(label,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${e(id)}">${label}</button>`;
const trip=()=>get(state,local.activeTrip);
const sets=()=>active(state,'set').filter(s=>s.tripId===local.activeTrip);
const fieldsets=()=>sets().sort((a,b)=>b.startedAt.localeCompare(a.startedAt));
const fieldAssets=()=>active(state,'asset').filter(a=>a.tripId===local.activeTrip);
const notice=(text,error=false)=>{clearTimeout(toastTimer);$('#notice').textContent=text;$('#notice').className='show'+(error?' error':'');toastTimer=setTimeout(()=>$('#notice').className='',error?10000:4500);};
function labelFields(root){for(const label of root.querySelectorAll('label:not([for])')){const input=label.nextElementSibling;if(input?.matches('input,select,textarea')){input.id ||= 'field-'+uid();label.htmlFor=input.id;}}}
function show(html){modal.innerHTML=html;labelFields(modal);modal.showModal();}
function close(){modal.close();stopMeter();}
async function refresh(){snapshot=await store.read();state=snapshot.state;local=snapshot.local;for(const b of snapshot.blobs)if(!urls.has(b.id))urls.set(b.id,URL.createObjectURL(b.blob));}
function savedLabel(){const el=$('#saved');if(el)el.textContent=saving?'Saving…':formDirty?'Unsaved edit · leave field to save':'Saved on this device';}
async function change(fn,redraw=true){saving++;savedLabel();try{await store.change(fn);await refresh();if(redraw)render();}catch(err){notice('Not saved: '+err.message,true);throw err;}finally{saving--;savedLabel();}}
function patch(id,changes){return change(s=>{const r=get(s,id);if(!r)throw Error('Record no longer exists');put(s,revise(r,changes,local.device.id));});}
const dateKey=(value,tz)=>new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value));
const mapLink=s=>s.location?`https://www.google.com/maps/search/?api=1&query=${s.location.lat},${s.location.lng}`:`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent([s.name,s.city].filter(Boolean).join(', '))}`;
function gpsText(s){return s.location?`${s.location.lat.toFixed(5)}, ${s.location.lng.toFixed(5)}${s.location.accuracy!=null?' · ±'+Math.round(s.location.accuracy)+' m':''}${s.location.capturedAt?' · fix '+localTime(s.location.capturedAt,s.timezone):''}`:'Location not recorded';}

function connection(){ $('#connection').textContent=(navigator.onLine?'On device':'Offline')+' · '+(native?'Android app':'Web notebook'); }
function render(){
  const oldForm=$('#set-form'),focused=document.activeElement;
  const draft=formDirty&&view==='field'&&oldForm?.dataset.set===selected?{values:[...new FormData(oldForm)],focus:focused?.name,start:focused?.selectionStart,end:focused?.selectionEnd}:null;
  const links=[['field','⌖','Field'],['library','▦','Library'],['transfer','⇄','Transfer'],['settings','⚙','Trips & kit']];
  $('#nav').innerHTML=links.map(([v,icon,title])=>`<button data-action="nav" data-id="${v}" class="${view===v?'on':''}"><span>${icon}</span>${title}</button>`).join('');
  connection();
  if(!trip()&&view!=='settings'&&view!=='transfer'){app.innerHTML=welcome();return;}
  if(view==='field')app.innerHTML=selected&&get(state,selected)&&!get(state,selected).deleted?editor(get(state,selected)):field();
  if(view==='library')app.innerHTML=library();
  if(view==='transfer')app.innerHTML=transfer();
  if(view==='settings')app.innerHTML=settings();
  formDirty=!!draft;labelFields(app);
  if(draft&&$('#set-form')){const form=$('#set-form');for(const [name,value]of draft.values)if(form.elements[name])form.elements[name].value=value;const input=form.elements[draft.focus];if(input){input.focus({preventScroll:true});if(draft.start!=null&&input.setSelectionRange)input.setSelectionRange(draft.start,draft.end);}}
  savedLabel();
  $('#update').hidden=!updateReady;
}
function welcome(){return `<div class="split"><section class="card hero"><div class="eyebrow" style="color:#d8e891">A field notebook for the way you see</div><h1>Bring the place<br>back with you.</h1><p class="muted">Sony originals. Phone observations. One connected reference library.</p>${button('Start a trip','new-trip','','primary')}</section><section class="card"><h2>From street to studio</h2><p>01 &nbsp; Capture a place and photograph its code.</p><p>02 &nbsp; Save light readings, reference photos and observations.</p><p>03 &nbsp; Match camera originals on your computer and prepare a review package.</p><small>Works offline after the first load. Hong Kong is an optional starting itinerary.</small></section></div>`;}
function field(){const t=trip(),all=fieldsets(),open=all.filter(s=>!s.endedAt),readings=active(state,'reading').filter(r=>r.tripId===t.id);const last=all.find(s=>s.location);const light=last?daylight(dateKey(now(),last.timezone),last.location.lat,last.location.lng,last.timezone):null;
return `<div class="heading row between"><div><div class="eyebrow">${e(t.city||'Anywhere')} · ${e(t.timezone)}</div><h1>${e(t.name)}</h1></div>${button('Switch trip','nav','settings')}</div>
<div class="split"><section class="card hero"><span class="tag live">FIELD CAPTURE</span><h2 style="font-size:29px;margin-top:18px">Found something worth keeping?</h2><p class="muted">Start a photo set anywhere. Photograph its code with your Sony, then get back to the scene.</p>${button('+ Capture here','capture','','primary')}${open.length?`<p>${open.length} open set${open.length>1?'s':''} · ${button('Continue '+e(open[0].code),'open',open[0].id)}</p>`:''}</section><section class="card"><div class="grid three"><div><div class="stat">${all.length}</div><small>Photo sets</small></div><div><div class="stat">${readings.length}</div><small>Light readings</small></div><div><div class="stat">${fieldAssets().length}</div><small>Images linked or waiting</small></div></div><hr class="divider">${light?`<small>Solar estimate at your last recorded position</small><p>${light.polar||`Sunrise ${localTime(light.rise,last.timezone)}<br>Sunset ${localTime(light.set,last.timezone)}`}</p><small>Buildings, hills and weather change the light on the street.</small>`:'<p class="muted">A GPS fix or manual coordinates unlock local sunrise and sunset estimates.</p>'}</section></div>
<div class="row between"><h2>Your stops</h2><small>Each return visit is a new photo set</small></div>${all.length?all.map(s=>`<section class="card"><div class="row between"><div><span class="tag ${s.endedAt?'':'live'}">${e(s.code)} · ${s.endedAt?'FINISHED':'OPEN'}</span><h2 style="margin-top:12px">${e(s.name||'Untitled stop')}</h2><small>${e(localTime(s.startedAt,s.timezone))} · ${e(s.city)}</small></div><div class="row">${button('Open','open',s.id,'primary')}${button('Revisit','revisit',s.id)}</div></div><p class="muted">${e(s.notes.slice(0,180)||'Add observations when you have a moment.')}</p></section>`).join(''):'<div class="empty">Your first capture starts here. No itinerary required.</div>'}
${t.template==='hongkong'?`<details class="card"><summary>Hong Kong itinerary · optional suggestions</summary>${days.map(d=>`<details><summary>${e(d.t)}</summary>${d.slots.map(([label,ids])=>`<small>${e(label)}</small>${ids.map(id=>{const p=places.find(p=>p.id===id);return `<div class="list-item row between"><div><b>${e(p.n)}</b><p class="muted">${e(p.d)}</p></div>${button('Capture here','place',id)}</div>`;}).join('')}`).join('')}</details>`).join('')}<small>Suggestions are inherited from the original itinerary. Check current access and opening times yourself.</small></details>`:''}`;}

function editor(s){const readings=active(state,'reading').filter(r=>r.setId===s.id),assets=active(state,'asset').filter(a=>a.setId===s.id);const exposure=ev100(Number(s.camera.aperture),shutterSeconds(s.camera.shutter),Number(s.camera.iso));
return `<div class="heading"><div class="row between">${button('‹ All stops','back')}<span id="saved" class="status"></span></div><div class="row between"><div><div class="eyebrow">${e(s.code)} · ${s.endedAt?'Finished':'Open photo set'}</div><h1>${e(s.name||'Untitled stop')}</h1></div>${button('Show camera slate','slate',s.id,'primary')}</div><small>${e(localTime(s.startedAt,s.timezone))}${s.endedAt?' → '+e(localTime(s.endedAt,s.timezone)):''} · ${e(s.timezone)}</small></div>
<div class="split"><div><section class="card"><h2>The place</h2><form id="set-form" data-set="${e(s.id)}"><div class="form-grid"><div class="wide"><label for="set-name">Location / subject</label><input id="set-name" name="name" maxlength="300" value="${e(s.name)}"></div><div><label>City / destination</label><input name="city" value="${e(s.city)}" maxlength="200"></div><div><label>Capture mode</label><select name="mode"><option value="quick" ${s.mode==='quick'?'selected':''}>Quick reference</option><option value="survey" ${s.mode==='survey'?'selected':''}>Lighting survey</option></select></div><div class="wide"><label>Observations</label><textarea name="notes" maxlength="4000" placeholder="Light sources, weather, materials, useful angles…">${e(s.notes)}</textarea></div></div><div class="row">${button('Get fresh GPS','gps',s.id)}${button('Enter coordinates','coords',s.id)}<a class="button quiet" href="${e(mapLink(s))}" target="_blank" rel="noopener">Open map ↗</a></div><p class="muted" style="font-size:12px">${e(gpsText(s))}</p><details><summary>Camera snapshot and file boundaries</summary><div class="form-grid"><div><label>Camera (EXIF model name)</label><input name="cameraName" value="${e(s.camera.name)}" maxlength="200"></div><div><label>Fixed white balance, K</label><input name="wb" type="number" min="1000" max="50000" value="${e(s.camera.wb??'')}"></div><div><label>Aperture</label><input name="aperture" type="number" min="0.5" max="128" step="0.1" value="${e(s.camera.aperture??'')}"></div><div><label>ISO</label><input name="iso" type="number" min="1" value="${e(s.camera.iso||'')}"></div><div><label>Shutter, seconds or fraction</label><input name="shutter" value="${e(s.camera.shutter||'')}" placeholder="1/125"></div><div><label>First / last Sony filenames (optional)</label><input name="files" value="${e(s.files||'')}" placeholder="DSC01234 → DSC01258" maxlength="500"></div></div><small>Settings are saved with this set. Original EXIF remains authoritative for individual images. ${exposure!==null?'Exposure setting EV100: '+fmt(exposure)+'. This is not measured scene lux.':''}</small></details><p><button type="submit" class="primary">Save record</button></p><small>Edits save when you leave a field; wait for “Saved” before closing.</small></form></section>
<section class="card"><div class="row between"><h2>Reference images</h2>${button('+ Add images','photo',s.id)}</div><p class="muted">Small phone references and Sony previews. RAW originals stay on your computer.</p><div class="thumbs">${assets.map(a=>`<figure>${a.blobId&&urls.get(a.blobId)?`<img src="${urls.get(a.blobId)}" alt="${e(a.fileName)}">`:'<div class="empty">No preview</div>'}<figcaption>${e(a.fileName)} · ${e(a.role||'unclassified')}</figcaption><div class="row">${button('Color sample','color',a.id,'quiet')}${button('Edit','asset',a.id,'quiet')}</div></figure>`).join('')}</div></section>
</div><div><section class="card"><div class="row between"><h2>Lighting</h2><span class="tag">WITH PROVENANCE</span></div><p class="muted">Save readings at a named position. Keep the phone orientation consistent when comparing light.</p><div class="row">${button('Measure light','meter',s.id,'primary')}${button('Manual reading','reading',s.id)}</div>${readings.length?readings.map(r=>`<div class="list-item"><div class="row between"><b>${e(r.label||'Reading')}</b><span>${fmt(r.value)} ${r.method.endsWith('lux')?'lux':'EV100'}</span></div><p>${e(r.instrument)} · ${e(r.method.replaceAll('_',' '))}</p><small>${e(r.protocol)} · ${e(r.calibration)}</small>${r.samples?`<p class="muted">Range ${fmt(r.samples.min)}–${fmt(r.samples.max)} · ${r.samples.count} samples</p>`:''}<div>${button('Remove','delete',r.id,'quiet danger')}</div></div>`).join(''):'<p class="muted">No measurements yet. Missing readings stay empty.</p>'}${comparison(readings)}</section>
<section class="card"><h2>Before you leave</h2><p>□ Code photographed on the Sony<br>□ Establishing view and useful details<br>□ ${s.mode==='survey'?'Reference target and light readings<br>□ Brackets / lighting zones checked':'One representative reference frame'}</p><div class="alert">Sony lens cover: uncalibrated target. Image samples describe rendered color, not measured Kelvin or physical albedo.</div>${s.endedAt?button('Reopen this set','reopen',s.id):button('Finish photo set','finish',s.id,'primary')} ${button('Archive set','delete',s.id,'quiet danger')}</section></div></div>`;}
function comparison(rs){const a=rs.at(-2),b=rs.at(-1);return a&&b&&comparable(a,b)?`<div class="alert success">Last two comparable readings: ${fmt(b.value/a.value)}× · ${fmt(Math.log2(b.value/a.value))} stops (${e(b.label)} relative to ${e(a.label)}). Relative, uncalibrated comparison.</div>`:rs.length>1?'<small>Ratios are shown only for positive readings from the same instrument, method, orientation protocol and calibration status.</small>':'';}

function library(){const t=trip(),assets=fieldAssets().filter(a=>[a.fileName,a.role,a.notes,...(a.tags||[])].join(' ').toLowerCase().includes(search.toLowerCase())),clocks=active(state,'clock').filter(c=>c.tripId===t.id);return `<div class="heading"><div class="eyebrow">STUDIO REVIEW</div><h1>The reference library</h1><p class="muted">${e(t.name)} · Original files are never moved or rewritten.</p><div class="row">${button('Import camera catalogue','import','','primary')}${button('Camera clock segments','clocks')}${button('Confirm unique suggestions','confirm-suggestions')}</div></div><label for="search">Search filenames, roles and notes</label><input id="search" value="${e(search)}" placeholder="Concrete, neon, DSC01234…"><p><small>Run the desktop importer to prepare camera metadata and previews. Imports never assign a photo set without your confirmation.</small></p><div class="grid three">${assets.map(a=>{const hint=!a.setId&&a.source==='camera'?suggest(a,sets(),clocks):null;const set=get(state,a.setId);return `<section class="card asset">${a.blobId&&urls.has(a.blobId)?`<img loading="lazy" src="${urls.get(a.blobId)}" alt="${e(a.fileName)}">`:'<div class="empty">Preview unavailable</div>'}<h3 style="margin-top:12px">${e(a.fileName)}</h3><span class="tag ${set?'':'warn'}">${set?e(set.code):'UNRESOLVED'}</span> <span class="tag">${e(a.role||'unclassified')}</span><p class="muted">${e(a.notes||'')}</p><small>${e(a.originalRelativePath||'Phone reference')}${a.captureWall?'<br>Camera clock: '+e(a.captureWall):''}</small>${hint?`<p class="muted">${hint.sets.length===1?'Suggested: '+e(hint.sets[0].code):hint.sets.length>1?'Ambiguous: overlapping sets':e(hint.reason)+(hint.time?' · no closed set contains this time':'')}</p>`:''}<div class="row">${button('Assign / describe','asset',a.id)}${a.blobId?button('Color','color',a.id,'quiet'):''}</div></section>`;}).join('')}</div>${assets.length?'':'<div class="empty">Import camera previews, or add reference images while capturing a set.</div>'}`;}
function transfer(){const t=trip(),conflicts=state.conflicts,deleted=state.records.filter(r=>r.deleted);return `<div class="heading"><div class="eyebrow">DEVICE → STUDIO → DEVICE</div><h1>Bring everything together.</h1><p class="muted">Portable ZIP packages include records, previews and checksums. Imports merge changes.</p></div><div class="grid"><section class="card"><h2>Export ${e(t?.name||'a trip')}</h2><p>Keep an independent copy before clearing cards or browser data.</p><div class="row">${button('Field backup','export','backup','primary')}${button('Prepare AI handoff','export','handoff')}</div><p><small>${local.lastExport?'Last export handed to your device: '+e(localTime(local.lastExport,'UTC'))+' UTC. Destination and second-copy verification are still your responsibility.':'No export recorded on this device.'}</small></p><p><small>Active trip only · Large trips split into portable parts · originals excluded</small></p></section><section class="card"><h2>Import / verify a package</h2><p>Review additions and conflicts before applying. Reading a package also verifies its preview checksums.</p>${button('Choose package','import','','primary')}<p><small>Scout ZIP, desktop catalogue ZIP, or original v1 JSON backup.</small></p></section></div><section class="card"><h2>Desktop RAW importer</h2><p>After copying the Sony card, run this from the repository on your computer:</p><pre>npm run catalogue -- --input "D:/Photos/Trip/Originals" --output "D:/Photos/Trip/Review"</pre><p class="muted">Creates resumable metadata, previews and import batches. Choose each catalogue ZIP above, add a clock segment, and review suggested matches.</p><small>The importer reads originals. It never renames, moves, deletes or writes metadata into them.</small></section>
<section class="card"><h2>Conflicts · ${conflicts.length}</h2>${conflicts.map(c=>{const current=get(state,c.incoming.id);return `<div class="list-item"><b>${e(current.name||current.fileName||current.label||current.code||current.id)}</b><div class="grid"><div><p>This device ${current.deleted?'(deleted)':''}</p><pre>${e(JSON.stringify(current,null,2))}</pre>${button('Keep this version','resolve-local',c.id)}</div><div><p>Incoming ${c.incoming.deleted?'(deleted)':''}</p><pre>${e(JSON.stringify(c.incoming,null,2))}</pre>${button('Use incoming version','resolve-incoming',c.id)}</div></div></div>`;}).join('')||'<p class="muted">No conflicting edits.</p>'}</section><details class="card"><summary>Recover archived records · ${deleted.length}</summary>${deleted.map(r=>`<div class="list-item row between"><span>${e(r.kind)} · ${e(r.name||r.fileName||r.label||r.id)}</span>${button('Restore','restore',r.id)}</div>`).join('')}</details>${state.legacy.length?'<p class="muted">Original v1 metadata is retained in the export archive. Historical global settings are not asserted as capture facts.</p>':''}`;}
function settings(){const all=active(state,'trip');return `<div class="heading"><div class="eyebrow">MAKE IT YOUR FIELD NOTEBOOK</div><h1>Trips & equipment</h1></div><div class="grid"><section class="card"><div class="row between"><h2>Your trips</h2>${button('+ New trip','new-trip','','primary')}</div>${all.map(t=>`<div class="list-item row between"><div><b>${e(t.name)}</b><p class="muted">${e(t.city)} · ${e(t.timezone)}</p></div>${button(t.id===local.activeTrip?'Selected':'Use trip','select-trip',t.id,t.id===local.activeTrip?'quiet':'')}</div>`).join('')||'<p>No trips yet.</p>'}</section><section class="card"><h2>This device & camera defaults</h2><form id="kit-form"><label>Device label</label><input name="deviceName" value="${e(local.device.name)}" maxlength="160" required><label>Camera model (as shown in EXIF)</label><input name="camera" value="${e(local.camera||'ILCE-7CR')}" maxlength="200" required><div class="form-grid"><div><label>White balance default, K</label><input name="wb" type="number" min="1000" max="50000" value="${e(local.wb||'5500')}"></div><div><label>Aperture default</label><input name="aperture" type="number" min="0.5" max="128" step="0.1" value="${e(local.aperture||'')}"></div></div><p><button type="submit" class="primary">Save defaults</button></p><small>Only new sets use these defaults. Existing capture facts remain unchanged.</small></form></section></div><section class="card"><h2>Capture readiness</h2><p>□ Sony clock and phone time checked<br>□ Code photograph readable<br>□ RAW storage and battery ready<br>□ App opened once online, then tested offline<br>□ Previous shoot exported and verified</p><div class="alert">Live lux: Android sensor when available. iPhone and desktop browsers support manual readings. Camera EV is a separate estimate. No sensor is considered photographically calibrated.</div><p>Reference target: Sony lens cover (uncalibrated). A known neutral gray card improves exposure and color references.</p><small>Scout 2.0 · local files first · no analytics or automatic cloud/AI upload</small></section>`;}

async function newSet(name='Untitled stop',source=null){const t=trip();const time=now();const r=record('set',{tripId:t.id,createdDevice:local.device.id,code:'S-'+uid().replaceAll('-','').slice(0,10).toUpperCase(),name,city:source?.city||t.city,timezone:source?.timezone||t.timezone,startedAt:time,endedAt:null,mode:'quick',notes:'',tags:[],files:'',location:null,camera:{name:local.camera||'ILCE-7CR',wb:local.wb?Number(local.wb):5500,aperture:local.aperture?Number(local.aperture):null,iso:'',shutter:''}},local.device.id);await change(s=>{for(const old of active(s,'set').filter(x=>x.tripId===t.id&&!x.endedAt&&(x.createdDevice||x.device)===local.device.id))put(s,revise(old,{endedAt:time},local.device.id));put(s,r);});selected=r.id;view='field';render();await slate(r);}
async function slate(s){show(`<div class="slate"><span class="eyebrow">PHOTOGRAPH THIS WITH YOUR SONY</span><div class="code">${e(s.code)}</div><p>${e(s.name)} · ${e(s.city)}</p><canvas id="qr"></canvas><time id="slate-time"></time><p>${e(s.timezone)}<br><small>The code identifies the set; the clock helps correct camera timestamps.</small></p>${button('Continue recording','close','','primary')}</div>`);await QRCode.toCanvas($('#qr'),JSON.stringify({app:'scout',v:2,tripId:s.tripId,setId:s.id,code:s.code}),{width:260,margin:2,errorCorrectionLevel:'M'});const tick=()=>{if($('#slate-time'))$('#slate-time').textContent=localTime(now(),s.timezone,true);};tick();const timer=setInterval(tick,1000);modal.addEventListener('close',()=>clearInterval(timer),{once:true});}
function tripDialog(){show(`<h2>Start a trip</h2><form id="trip-form"><label>Trip name</label><input name="name" placeholder="Hong Kong · October references" required maxlength="200"><label>Starting city / destination</label><input name="city" placeholder="Hong Kong, Tokyo, or somewhere new" required maxlength="200"><label>Time zone</label><input name="timezone" value="${e(Intl.DateTimeFormat().resolvedOptions().timeZone)}" placeholder="Asia/Hong_Kong" required><label>Starting itinerary</label><select name="template"><option value="blank">Blank · explore anywhere</option><option value="hongkong">Hong Kong reference locations</option></select><p><small>Use an IANA time zone such as Asia/Hong_Kong, Asia/Tokyo or America/Los_Angeles. Each set preserves its capture zone.</small></p><div class="row"><button type="submit" class="primary">Create trip</button>${button('Cancel','close')}</div></form>`);}
function readingDialog(sid,measured=null){const s=get(state,sid);show(`<h2>${measured?'Save phone measurement':'Add lighting reading'}</h2><form id="reading-form" data-set="${e(sid)}"><label>Position / zone</label><input name="label" placeholder="Under awning, street center…" required maxlength="200"><div class="form-grid"><div><label>Method</label><select name="method" ${measured?'disabled':''}>${(measured?[['phone_lux','Phone sensor · lux']]:[['external_lux','External / manual lux'],['camera_ev','Camera meter · EV100'],['manual_ev','External meter · EV100']]).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></div><div><label>Value</label><input name="value" type="number" step="any" value="${measured?.value??''}" required ${measured?'readonly':''}></div></div><label>Instrument / source</label><input name="instrument" value="${e(measured?.instrument||'')}" placeholder="Meter model or measurement app" required maxlength="200"><label>Orientation / target protocol</label><input name="protocol" placeholder="Phone face upward, at 1.5 m / gray card spot reading…" required maxlength="500"><p><small>${measured?'Phone readings are uncalibrated. Stability is not accuracy.':'Enter the meter’s ISO-100 EV reading, not exposure compensation. Keep lux and camera EV separate.'}</small></p><div class="row"><button type="submit" class="primary">Save reading</button>${button('Cancel','close')}</div></form>`);sample=measured;}
async function meter(sid){sample=null;show(`<h2>Measure light</h2><p class="muted">Keep the sensor uncovered and the phone steady. A short sample starts when you tap below.</p><div class="metric" id="meter-value">—</div><p id="meter-status">Ready · phone lux is uncalibrated</p><div class="row">${button('Capture 4 seconds','meter-start',sid,'primary')}${button('Cancel','close')}</div>`);}
function assetDialog(id){const a=get(state,id);show(`<h2>Image association</h2><p>${e(a.fileName)}</p><details><summary>Original metadata & import notes</summary><p>${e(a.previewSource||'Phone reference preview')}</p><pre>${e(JSON.stringify(a.exif||{},null,2))}</pre><p>${e((a.warnings||[]).join(' · '))}</p></details><form id="asset-form" data-id="${e(id)}"><label>Photo set</label><select name="setId"><option value="">Unresolved</option>${sets().map(s=>`<option value="${e(s.id)}" ${s.id===a.setId?'selected':''}>${e(s.code+' · '+s.name)}</option>`).join('')}</select><label>Reference role</label><select name="role">${roles.map(r=>`<option ${r===a.role?'selected':''}>${e(r)}</option>`).join('')}</select><label>Tags (comma-separated)</label><input name="tags" value="${e((a.tags||[]).join(', '))}" maxlength="500"><label>Description / observations</label><textarea name="notes" maxlength="4000">${e(a.notes||'')}</textarea><small>${e(a.originalRelativePath||'Phone reference')}<br>${e(a.sha256||'')}</small><p><button type="submit" class="primary">Save association</button> ${button('Cancel','close')}</p></form>${button('Archive image record','delete',id,'quiet danger')}`);}
function clocksDialog(){const clocks=active(state,'clock').filter(c=>c.tripId===local.activeTrip),cameras=[...new Set([local.camera||'ILCE-7CR',...fieldAssets().map(a=>a.camera).filter(Boolean)])];show(`<h2>Camera clock correction</h2><p>Keep the original camera time. These segments only interpret it for matching. Photograph the phone clock to establish each correction.</p>${clocks.map(c=>`<div class="list-item"><b>${e(c.camera)}</b><p>${e(c.from.slice(0,16))} → ${e(c.to.slice(0,16))}<br>UTC offset ${c.utcOffsetMinutes/60} h · correction ${c.offsetSeconds} s</p>${button('Remove segment','delete',c.id,'quiet danger')}</div>`).join('')}<form id="clock-form"><label>Camera model</label><select name="camera">${cameras.map(c=>`<option>${e(c)}</option>`).join('')}</select><label>Camera wall time · from</label><input type="datetime-local" name="from" required><label>Camera wall time · to</label><input type="datetime-local" name="to" required><div class="form-grid"><div><label>Camera UTC offset (hours)</label><input name="zone" type="number" min="-14" max="14" step="0.25" value="8" required></div><div><label>Add seconds to camera time</label><input name="offset" type="number" min="-172800" max="172800" step="0.1" value="0" required></div></div><p><small>If the camera is 90 seconds slow, enter +90. Use separate segments after clock or time-zone changes. Overlapping segments block suggestions.</small></p><button type="submit" class="primary">Add segment</button> ${button('Close','close')}</form>`);}
function saveSetForm(form,redraw=false){
  const sid=selected,version=editVersion,f=new FormData(form);
  const fields={name:String(f.get('name')).trim(),city:String(f.get('city')).trim(),mode:f.get('mode'),notes:f.get('notes'),files:f.get('files'),camera:{name:String(f.get('cameraName')).trim()||'Unknown camera',wb:f.get('wb')?Number(f.get('wb')):null,aperture:f.get('aperture')?Number(f.get('aperture')):null,iso:f.get('iso')||'',shutter:f.get('shutter')||''}};
  const save=async()=>{const base=get(state,sid);if(!base)return;
    const changed=Object.fromEntries(Object.entries(fields).filter(([k,v])=>JSON.stringify(v)!==JSON.stringify(base[k])));
    if(!Object.keys(changed).length){if(version===editVersion)formDirty=false;savedLabel();return;}
    const incoming=revise(base,changed,local.device.id);let conflicts=0;
    await change(st=>{const result=merge(st,[incoming],uid());conflicts=result.conflicts;Object.assign(st,result.state);},redraw);
    if(version===editVersion)formDirty=false;savedLabel();
    if(conflicts)notice('Another tab changed this record. Both versions are in Transfer → Conflicts.',true);
  };
  formSave=formSave.catch(()=>{}).then(save);return formSave;
}

async function importFile(file){if(file.size>MAX_PACKAGE)throw Error('Import limit is 64 MiB. Use smaller desktop batches.');notice('Reading package and checking attachments…');
  if(file.name.toLowerCase().endsWith('.json')){const p=JSON.parse(await file.text());if(p.v===1){const records=migrateLegacy(p,'legacy-import');const blobs=[];for(const [id,o]of Object.entries(p.photoData||{})){if(typeof o.d!=='string'||!/^data:image\/(jpeg|png|webp);base64,/.test(o.d))throw Error('Unsupported legacy photo');const bytes=Uint8Array.from(atob(o.d.split(',')[1]),c=>c.charCodeAt(0));const bid='legacy-'+id,blob=new Blob([bytes],{type:o.d.slice(5,o.d.indexOf(';'))});blobs.push({id:bid,blob,sha256:await sha256(bytes)});const parent=records.find(r=>r.kind==='set'&&r.legacyPoint?.id===o.pointId);if(parent){const r=record('asset',{tripId:'legacy-hk',setId:parent.id,fileName:'Legacy reference '+id,source:'field',blobId:bid,notes:'Original v1 compressed reference.',role:'unclassified'},'legacy-v1','legacy-image-'+id);r.revision=r.id+'-v1';r.updatedAt=parent.startedAt;records.push(r);}}const archive={...p};delete archive.photoData;pendingImport={packet:{packageId:'legacy-'+await sha256(new TextEncoder().encode(JSON.stringify(p))),records,legacy:[archive]},blobs};}
    else throw Error('Use the desktop catalogue ZIP so previews and checksums travel with the metadata.');
  }else{const files=unpack(new Uint8Array(await file.arrayBuffer()));if(files['field.json'])pendingImport=await decodeField(files);else if(files['catalogue.json']){await importCatalogue(files);return;}else throw Error('Unrecognized ZIP package.');}
  const preview=merge(state,pendingImport.packet.records,pendingImport.packet.packageId);show(`<h2>Review import</h2><p>${preview.added} new records · ${preview.updated} newer versions · ${preview.conflicts} conflicts</p><p>${pendingImport.blobs.length} verified image attachments</p>${preview.duplicate?'<div class="alert">This package has already been imported.</div>':''}<p>Conflicting versions are retained for review. Older packages cannot silently undo newer records.</p><div class="row">${button('Apply merge','apply-import','','primary')}${button('Cancel','close')}</div>`);
}
async function importCatalogue(files){if(!trip())throw Error('Select or create the destination trip first.');const p=JSON.parse(strFromU8(files['catalogue.json']));if(p.format!=='scout-camera'||p.schemaVersion!==1||!Array.isArray(p.assets)||p.assets.length>1000)throw Error('Unsupported camera catalogue.');const records=[],blobs=[];let duplicates=0;
  for(const a of p.assets){if(!/^[a-f0-9]{64}$/.test(a.sha256)||typeof a.fileName!=='string'||typeof a.originalRelativePath!=='string')throw Error('Invalid camera file manifest.');const id='camera-'+trip().id+'-'+a.sha256;if(get(state,id)){duplicates++;continue;}let blobId=null;if(a.previewPath){const bytes=files[a.previewPath];if(!bytes||await sha256(bytes)!==a.previewSha256)throw Error('Missing or corrupt camera preview: '+a.fileName);blobId='preview-'+a.sha256;blobs.push({id:blobId,blob:new Blob([bytes],{type:'image/jpeg'}),sha256:a.previewSha256});}
    records.push(record('asset',{tripId:trip().id,setId:null,source:'camera',fileName:a.fileName,originalRelativePath:a.originalRelativePath,duplicatePaths:a.duplicatePaths||[],sha256:a.sha256,blobId,captureWall:a.captureWall||null,camera:a.camera||'Unknown camera',previewSource:a.previewSource||'Imported preview',exif:a.exif||{},warnings:a.warnings||[],role:'unclassified',notes:'',tags:[]},local.device.id,id));
  }
  validateRecords(records);pendingImport={catalogue:true,packet:{records,packageId:'camera-batch-'+await sha256(files['catalogue.json'])},blobs};show(`<h2>Camera catalogue</h2><p>${records.length} new camera files · ${duplicates} already catalogued · ${blobs.length} previews</p><p>Files will enter the unresolved inbox for ${e(trip().name)}. Review the clock correction and suggested associations afterward.</p><div class="row">${button('Import catalogue','apply-import','','primary')}${button('Cancel','close')}</div>`);
}
async function applyImport(){const item=pendingImport;if(!item)return;const existing=new Map(snapshot.blobs.map(b=>[b.id,b]));for(const b of item.blobs){const old=existing.get(b.id);if(old&&await sha256(await old.blob.arrayBuffer())!==b.sha256)throw Error('Attachment ID collision. No changes applied.');}
 await change((s,b,l)=>{if(item.catalogue){for(const r of item.packet.records)if(!get(s,r.id))put(s,r);if(!s.packages.includes(item.packet.packageId))s.packages.push(item.packet.packageId);}else{const merged=merge(s,item.packet.records,item.packet.packageId);Object.assign(s,merged.state);for(const legacy of item.packet.legacy||[])if(!s.legacy.some(x=>JSON.stringify(x)===JSON.stringify(legacy)))s.legacy.push(legacy);}for(const blob of item.blobs)b.put(blob);if(!l.activeTrip)l.activeTrip=active(s,'trip')[0]?.id;});pendingImport=null;close();view=item.catalogue?'library':'transfer';selected=null;render();notice('Import committed. Originals unchanged.');}

async function addPhotos(files,sid){let success=0;const failures=[];for(const file of files){try{if(file.size>40*1024*1024)throw Error('Image exceeds 40 MiB. Use the desktop importer for RAW / large originals.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height));const c=document.createElement('canvas');c.width=Math.round(bitmap.width*scale);c.height=Math.round(bitmap.height*scale);c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.85));if(!blob)throw Error('Image conversion failed');const id=uid(),bytes=await blob.arrayBuffer(),hash=await sha256(bytes);await change((s,b)=>{const set=get(s,sid);if(!set||set.deleted)throw Error('Photo set is archived');b.put({id,blob,sha256:hash});put(s,record('asset',{tripId:set.tripId,setId:sid,source:'field',fileName:file.name,blobId:id,role:'unclassified',notes:'',tags:[],attachedAt:now()},local.device.id));},false);success++;}catch(err){failures.push(file.name+': '+err.message);}}
 render();notice(`${success} photo${success===1?'':'s'} saved${failures.length?'; '+failures.length+' failed':''}`,!!failures.length);if(failures.length)show(`<h2>Photo import results</h2><p>${success} saved.</p><pre>${e(failures.join('\n'))}</pre>${button('Close','close')}`);
}
async function colorDialog(id){const a=get(state,id),url=urls.get(a.blobId);if(!url)throw Error('This asset has no preview');show(`<h2>Image color reference</h2><p>Click a matte, unclipped area. This samples the rendered preview, not RAW sensor values.</p><canvas id="color-canvas"></canvas><div id="color-result"></div><label>Target / interpretation</label><input id="color-target" value="Sony lens cover · uncalibrated" maxlength="200"><p><small>Keep lighting appearance and neutralized material references separate. This does not measure CCT or physical albedo.</small></p>${button('Save sample in image notes','save-color',id,'primary')} ${button('Close','close')}`);const img=new Image();await new Promise((resolve,reject)=>{img.onload=resolve;img.onerror=reject;img.src=url;});const canvas=$('#color-canvas');const scale=Math.min(1,900/img.width);canvas.width=img.width*scale;canvas.height=img.height*scale;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(img,0,0,canvas.width,canvas.height);sample=null;
 canvas.onclick=event=>{const rect=canvas.getBoundingClientRect(),x=Math.round((event.clientX-rect.left)*canvas.width/rect.width),y=Math.round((event.clientY-rect.top)*canvas.height/rect.height),left=Math.max(0,x-5),top=Math.max(0,y-5),w=Math.min(11,canvas.width-left),h=Math.min(11,canvas.height-top);const px=ctx.getImageData(left,top,w,h).data,linear=[0,0,0];let clipped=0;for(let i=0;i<px.length;i+=4){for(let j=0;j<3;j++){let v=px[i+j]/255;linear[j]+=v<=.04045?v/12.92:((v+.055)/1.055)**2.4;}if(px[i]>245||px[i+1]>245||px[i+2]>245)clipped++;}linear.forEach((v,i)=>linear[i]=v/(px.length/4));const rgb=linear.map(v=>Math.round(255*(v<=.0031308?v*12.92:1.055*v**(1/2.4)-.055))),hex='#'+rgb.map(v=>v.toString(16).padStart(2,'0')).join('');sample={rgb,hex,x:x/canvas.width,y:y/canvas.height,linear,clipped};$('#color-result').innerHTML=`<p class="row"><span class="color-chip" style="background:${hex}"></span><b>${hex.toUpperCase()}</b> · sRGB ${rgb.join(', ')}</p>${clipped?'<div class="alert">Some samples are near clipping. Choose another area.</div>':''}`;};
}

document.addEventListener('click',async event=>{const el=event.target.closest('[data-action]');if(!el)return;event.preventDefault();const action=el.dataset.action,id=el.dataset.id;try{
 if(!['save-color','close'].includes(action)&&$('#set-form'))await saveSetForm($('#set-form'));
 if(action==='nav'){stopMeter();view=id;selected=null;render();window.scrollTo(0,0);}
 if(action==='back'){selected=null;render();}
 if(action==='new-trip')tripDialog();
 if(action==='select-trip'){await change((s,b,l)=>{l.activeTrip=id;});selected=null;view='field';render();}
 if(action==='capture')await newSet();
 if(action==='place'){const p=places.find(p=>p.id===id);await newSet(p.n);}
 if(action==='revisit'){const s=get(state,id);await newSet(s.name,s);}
 if(action==='open'){selected=id;view='field';render();window.scrollTo(0,0);}
 if(action==='slate')await slate(get(state,id));
 if(action==='close')close();
 if(action==='finish'){await patch(id,{endedAt:now()});notice('Set finished. The time boundary is saved.');}
 if(action==='reopen'){if(!confirm('Reopen this interval? New photographs may be included in timestamp suggestions.'))return;await change(s=>{for(const other of active(s,'set').filter(x=>x.tripId===local.activeTrip&&!x.endedAt&&x.id!==id))put(s,revise(other,{endedAt:now()},local.device.id));put(s,revise(get(s,id),{endedAt:null},local.device.id));});}
 if(action==='gps'){el.disabled=true;el.textContent='Locating…';const location=await locate();await patch(id,{location});notice(location.accuracy>50?'Saved GPS with low accuracy. Add a landmark note.':'Fresh location saved.');}
 if(action==='coords'){const s=get(state,id);show(`<h2>Location & time zone</h2><form id="coords-form" data-id="${e(id)}"><div class="form-grid"><div><label>Latitude (WGS84)</label><input name="lat" type="number" step="any" min="-90" max="90" value="${e(s.location?.lat??'')}" required></div><div><label>Longitude (WGS84)</label><input name="lng" type="number" step="any" min="-180" max="180" value="${e(s.location?.lng??'')}" required></div></div><label>Capture time zone</label><input name="timezone" value="${e(s.timezone)}" required><p><small>Entering coordinates does not claim a GPS fix. Time-zone changes affect display, not the original capture instant.</small></p><button type="submit" class="primary">Save location</button> ${button('Cancel','close')}</form>`);}
 if(action==='meter')await meter(id);
 if(action==='meter-start'){el.disabled=true;$('#meter-status').textContent='Sampling…';const result=await measureLight(v=>{if($('#meter-value'))$('#meter-value').textContent=fmt(v);});if(modal.open&&$('#meter-status'))readingDialog(id,{...result,instrument:result.instrument+' · '+local.device.name+' ['+local.device.id.slice(0,8)+']'});}
 if(action==='reading'){sample=null;readingDialog(id);}
 if(action==='photo'){$('#photo-file').dataset.set=id;$('#photo-file').value='';$('#photo-file').click();}
 if(action==='asset')assetDialog(id);
 if(action==='color')await colorDialog(id);
 if(action==='save-color'){if(!sample?.rgb)throw Error('Choose an image sample first.');const a=get(state,id);const note=`Image-derived sRGB ${sample.rgb.join(', ')} (${sample.hex}) at ${sample.x.toFixed(3)},${sample.y.toFixed(3)}; target: ${$('#color-target').value}; uncalibrated rendered preview; ${sample.clipped?'near-clipping pixels present':'no near-clipping pixels in sample'}.`;await patch(id,{notes:[a.notes,note].filter(Boolean).join('\n')});close();notice('Color sample saved with the image.');}
 if(action==='delete'){if(!confirm('Archive this record? It can be restored from Transfer. Originals stay untouched.'))return;await patch(id,{deleted:true});if(modal.open)close();render();}
 if(action==='restore')await patch(id,{deleted:false});
 if(action==='import'){$('#import-file').value='';$('#import-file').click();}
 if(action==='apply-import'){el.disabled=true;await applyImport();}
 if(action==='resolve-local'||action==='resolve-incoming')await change(s=>resolve(s,id,action==='resolve-incoming',local.device.id));
 if(action==='export'){if(!trip())throw Error('Create a trip first');el.disabled=true;await refresh();pendingExports=await exportTrip(snapshot,trip().id,id==='handoff');if(pendingExports.length===1){await deliver(pendingExports[0].filename,pendingExports[0].bytes);await change((s,b,l)=>{l.lastExport=now();});notice('Package handed to your device. Verify the saved file and second copy.');pendingExports=[];}else{show('<h2>Save all '+pendingExports.length+' parts</h2><p>Import every part on the other device. Shared field records merge without duplication. Keep this window open until every part is saved.</p>'+pendingExports.map((x,i)=>'<p>'+button('Save part '+(i+1)+' / '+pendingExports.length,'save-part',String(i),'primary')+' <small>'+e(x.filename)+'</small></p>').join('')+button('Close','close'));}}
 if(action==='save-part'){const x=pendingExports[Number(id)];if(!x)throw Error('Create the export again.');await deliver(x.filename,x.bytes);await change((s,b,l)=>{l.lastExport=now();},false);el.textContent='Part '+(Number(id)+1)+' handed to device · save again';}
 if(action==='clocks')clocksDialog();
 if(action==='confirm-suggestions'){const clocks=active(state,'clock').filter(c=>c.tripId===local.activeTrip),candidates=fieldAssets().filter(a=>!a.setId&&a.source==='camera').map(a=>({a,result:suggest(a,sets(),clocks)})).filter(x=>x.result.sets.length===1);if(!candidates.length)throw Error('No unique suggestions. Add clock segments and finish photo-set intervals first.');if(!confirm(`Confirm ${candidates.length} timestamp suggestions? Check your clock segments and set boundaries first. You can change each association later.`))return;await change(s=>{for(const {a,result}of candidates)put(s,revise(get(s,a.id),{setId:result.sets[0].id,association:{method:'time-confirmed',correctedTime:result.time,confirmedAt:now()}},local.device.id));});}
 if(action==='update-app'){if(saving)throw Error('Wait for the current save to finish.'); const reg=await navigator.serviceWorker.getRegistration();if(reg?.waiting){navigator.serviceWorker.addEventListener('controllerchange',()=>location.reload(),{once:true});reg.waiting.postMessage({type:'ACTIVATE'});}else notice('Already up to date.');}
 }catch(err){notice(err.name==='AbortError'?'Cancelled. No export confirmation recorded.':err.message,true);}finally{if(el.isConnected)el.disabled=false;if(action==='gps'&&el.isConnected)el.textContent='Get fresh GPS';}});

document.addEventListener('submit',async event=>{event.preventDefault();const form=event.target,f=new FormData(form),submit=form.querySelector('[type=submit]');if(submit)submit.disabled=true;try{
 if(form.id==='trip-form'){const tz=f.get('timezone').trim();if(!timezoneValid(tz))throw Error('Enter a valid IANA time zone.');const r=record('trip',{name:f.get('name').trim(),city:f.get('city').trim(),timezone:tz,template:f.get('template')},local.device.id);await change((s,b,l)=>{put(s,r);l.activeTrip=r.id;});close();view='field';selected=null;render();}
 if(form.id==='kit-form'){await change((s,b,l)=>{l.device.name=f.get('deviceName').trim();l.camera=f.get('camera').trim();l.wb=f.get('wb');l.aperture=f.get('aperture');});notice('Defaults saved for new sets.');}
 if(form.id==='set-form'){await saveSetForm(form,true);notice('Record saved.');}
 if(form.id==='coords-form'){const timezone=f.get('timezone').trim();if(!timezoneValid(timezone))throw Error('Invalid time zone');await patch(form.dataset.id,{timezone,location:{lat:Number(f.get('lat')),lng:Number(f.get('lng')),accuracy:null,capturedAt:now(),method:'manual'}});close();}
 if(form.id==='reading-form'){const set=get(state,form.dataset.set),measured=sample;const method=measured?'phone_lux':f.get('method'),value=Number(f.get('value'));if(!Number.isFinite(value)||method.endsWith('lux')&&value<0)throw Error('Enter a valid reading');const r=record('reading',{tripId:set.tripId,setId:set.id,label:f.get('label').trim(),method,value,instrument:f.get('instrument').trim(),protocol:f.get('protocol').trim(),calibration:measured?'Uncalibrated phone sensor':'Calibration not verified',measuredAt:now(),samples:measured?{min:measured.min,max:measured.max,count:measured.count,durationMs:measured.durationMs}:null},local.device.id);await change(s=>put(s,r));sample=null;close();notice('Measurement saved.');}
 if(form.id==='asset-form'){await patch(form.dataset.id,{setId:f.get('setId')||null,role:f.get('role'),tags:f.get('tags').split(',').map(s=>s.trim()).filter(Boolean),notes:f.get('notes'),association:{method:'manual',confirmedAt:now()}});close();}
 if(form.id==='clock-form'){const r=record('clock',{tripId:trip().id,camera:f.get('camera'),from:new Date(f.get('from')+'Z').toISOString(),to:new Date(f.get('to')+'Z').toISOString(),utcOffsetMinutes:Number(f.get('zone'))*60,offsetSeconds:Number(f.get('offset'))},local.device.id);await change(s=>put(s,r));clocksDialog();}
 }catch(err){notice(err.message,true);}finally{if(submit?.isConnected)submit.disabled=false;}});
document.addEventListener('change',async event=>{try{if(event.target.matches('#trip-form [name=template]')&&event.target.value==='hongkong'){const form=event.target.form;form.elements.timezone.value='Asia/Hong_Kong';if(!form.elements.city.value)form.elements.city.value='Hong Kong';}if(event.target.closest('#set-form'))await saveSetForm($('#set-form'));}catch{}});
$('#photo-file').addEventListener('change',event=>{const files=[...event.target.files],sid=event.target.dataset.set;addPhotos(files,sid).catch(err=>notice(err.message,true));});
$('#import-file').addEventListener('change',event=>{if(event.target.files[0])importFile(event.target.files[0]).catch(err=>notice(err.message,true));});
document.addEventListener('input',event=>{if(event.target.id==='search'){search=event.target.value;const pos=event.target.selectionStart;render();$('#search').focus();$('#search').setSelectionRange(pos,pos);}else if(event.target.closest('#set-form')){formDirty=true;editVersion++;const el=$('#saved');if(el)el.textContent='Unsaved edit · leave field to save';}});
window.addEventListener('beforeunload',event=>{if(saving||$('#saved')?.textContent.startsWith('Unsaved')){event.preventDefault();event.returnValue='';}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&$('#set-form'))saveSetForm($('#set-form')).catch(()=>{});});
modal.addEventListener('close',()=>{stopMeter();});
window.addEventListener('online',connection);window.addEventListener('offline',connection);

async function legacyMigration(){if(local.legacyMigrated)return;let raw;try{raw=localStorage.getItem('hkscout_v1');}catch{}if(!raw){await change((s,b,l)=>l.legacyMigrated=true,false);return;}
 const old=JSON.parse(raw),records=migrateLegacy(old,'legacy-browser');let photos=[];
 photos=await new Promise((resolve,reject)=>{const q=indexedDB.open('hkscout');let created=false;q.onupgradeneeded=()=>created=true;q.onerror=()=>reject(q.error);q.onsuccess=()=>{const db=q.result;if(created||!db.objectStoreNames.contains('photos')){db.close();resolve([]);return;}const tx=db.transaction('photos');const a=tx.objectStore('photos').getAll();tx.oncomplete=()=>{db.close();resolve(a.result||[]);};tx.onerror=()=>reject(tx.error);};});
 const blobs=[];for(const p of photos){const parent=records.find(r=>r.kind==='set'&&r.legacyPoint?.id===p.pointId);if(!parent)continue;const id='legacy-'+p.id;blobs.push({id,blob:p.blob,sha256:await sha256(await p.blob.arrayBuffer())});const r=record('asset',{tripId:'legacy-hk',setId:parent.id,source:'field',fileName:'Legacy reference '+p.id,blobId:id,role:'unclassified',notes:'Original v1 compressed reference.'},'legacy-v1','legacy-image-'+p.id);r.revision=r.id+'-v1';r.updatedAt=parent.startedAt;records.push(r);}
 await change((s,b,l)=>{for(const r of records)put(s,r);for(const blob of blobs)b.put(blob);s.legacy.push(old);l.legacyMigrated=true;l.activeTrip='legacy-hk';},false);notice('Your original Hong Kong records were migrated. The v1 source was preserved.');
}
async function boot(){try{await store.open();await refresh();await legacyMigration();render();if(sets().some(s=>!s.endedAt))notice('An open photo set was recovered. Continue it or finish it before moving on.');navigator.storage?.persist?.().catch(()=>{});if('serviceWorker'in navigator&&!native&&location.protocol!=='file:'){const reg=await navigator.serviceWorker.register('./sw.js');const offer=()=>{updateReady=!!reg.waiting;$('#update').hidden=!updateReady;if(updateReady)notice('An app update is ready. Use Update app when your capture is saved.');};reg.addEventListener('updatefound',()=>reg.installing?.addEventListener('statechange',offer));offer();}}catch(err){app.innerHTML=`<section class="card"><h1>Could not open the notebook</h1><p>${e(err.message)}</p><p>Your existing browser data has not been cleared. Export the v1 data from another existing tab if migration needs repair.</p></section>`;}}
boot();
