import {h as html,t as tr} from './i18n.js';
import {escapeHTML as e} from './packets.js';
import {get,active} from './model.js';
import {workspaceAssets} from './workspace.js';

export function workspaceHTML({studio,state,trip,assets,selection,filter,search,stop,camera,urls,button,roles,reviewId,undo,localTime}){
 const all=workspaceAssets(state,trip.id),stops=active(state,'set').filter(s=>s.tripId===trip.id),cameras=[...new Set(all.filter(a=>a.source==='camera').map(a=>a.camera).filter(Boolean))];
 const filters=[['all','All files'],['unassigned','Unassigned'],['phone','Phone references'],['camera','Camera files'],['trash','Project Trash']];
 const reviewing=get(state,reviewId),review=reviewing?.tripId===trip.id&&!reviewing.deleted?reviewing:null,scene=get(state,review?.setId),vibe=scene&&all.find(a=>a.setId===scene.id&&a.source==='field'&&a.role==='vibe'),light=scene&&active(state,'reading').filter(r=>r.setId===scene.id).sort((a,b)=>b.measuredAt.localeCompare(a.measuredAt))[0];
 return html`<div class="workspace-heading"><div><div class="eyebrow">SCOUT WORKSPACE</div><h1>${e(trip.name)}</h1><p class="muted">Bring the place back. Build your reference library.</p></div><div class="row">${studio?button('Import phone ZIP','import')+button('Add camera folder','camera-folder','','primary')+button('Add camera files','camera-files','','quiet'):button('Send to PC','workspace-nav','transfer','primary')}</div></div>
 <div class="workspace-layout"><aside class="workspace-sidebar"><label for="workspace-trip">Trip</label><select id="workspace-trip">${active(state,'trip').map(t=>html`<option value="${e(t.id)}" ${trip.id===t.id?'selected':''}>${e(t.name)}</option>`).join('')}</select><div class="workspace-filters">${filters.map(([id,label])=>html`<button data-action="workspace-filter" data-id="${id}" class="${filter===id?'on':''}" aria-pressed="${filter===id}"><span>${tr(label)}</span><b>${workspaceAssets(state,trip.id,{filter:id}).length}</b></button>`).join('')}</div><div class="workspace-tools">${button('Stops & field data','workspace-nav','field','quiet')}${button('Camera clock segments','clocks','','quiet')}${button('Confirm unique suggestions','confirm-suggestions','','quiet')}${button('Import camera catalogue','import','','quiet')}${button('Trips & kit','workspace-nav','settings','quiet')}</div><small>Originals stay in your camera folders. Scout stores a catalogue and previews.</small></aside>
 <section class="workspace-content"><div class="workspace-toolbar"><div class="workspace-search"><label class="sr-only" for="search">Search filenames, roles and notes</label><input type="search" id="search" value="${e(search)}" placeholder="Search files, cameras, roles or notes"></div><select id="workspace-stop" aria-label="Filter by stop"><option value="">All stops</option>${stops.map(s=>html`<option value="${e(s.id)}" ${stop===s.id?'selected':''}>${e(s.code+' · '+s.name)}</option>`).join('')}</select><select id="workspace-camera" aria-label="Filter by camera"><option value="">All cameras</option>${cameras.map(c=>html`<option ${camera===c?'selected':''} value="${e(c)}">${e(c)}</option>`).join('')}</select></div>
 <div class="selection-bar"><b>${tr('Selected images')}: ${selection.size}</b><span>${assets.length} ${tr('shown')}</span><div class="row">${button('Select shown','select-images','','quiet')}${selection.size?button('Clear selection','clear-images','','quiet'):''}</div></div>
 ${filter==='trash'?html`<div class="workspace-hint">Trash keeps files until you delete them permanently. Restore here, or permanently remove selected Scout copies.</div>`:html`<div class="workspace-hint">Click a tile to select. Shift selects a range. Ctrl / ⌘ A selects all shown.</div>`}
 ${undo?html`<div class="undo-bar" role="status"><span>Files moved to Project Trash.</span>${button('Undo','undo-trash')}</div>`:''}
 <div class="contact-sheet">${assets.map(a=>{const s=get(state,a.setId),checked=selection.has(a.id);return html`<article class="asset file-tile ${checked?'selected':''}"><div class="tile-select"><input type="checkbox" data-select-image="${e(a.id)}" aria-label="${tr('Select image')+' '+e(a.fileName)}" ${checked?'checked':''}><span>${tr(a.source==='field'?'Phone reference':'Camera file')}</span></div><button class="tile-preview" data-action="select-asset" data-id="${e(a.id)}" aria-label="${tr('Select image')+' '+e(a.fileName)}" aria-pressed="${checked}">${a.blobId&&urls.has(a.blobId)?html`<img loading="lazy" src="${urls.get(a.blobId)}" alt="${e(a.fileName)}">`:html`<div class="missing-preview"><b>${e(a.fileName.split('.').at(-1).toUpperCase())}</b><small>Preview unavailable</small></div>`}<strong>${e(a.fileName)}</strong></button><div class="tile-meta"><span class="tag ${s?'':'warn'}">${s?e(s.code):tr('UNRESOLVED')}</span><span>${e(tr(a.role||'unclassified'))}</span></div><small class="tile-camera">${e(a.camera||tr('Phone reference'))}</small><div class="tile-actions">${filter==='trash'?button('Restore','restore-asset',a.id):button('Review','review-asset',a.id)+button('Assign / describe','asset',a.id,'quiet')}</div></article>`;}).join('')}</div>
 ${assets.length?'':html`<div class="empty workspace-empty"><h2>No files here yet</h2><p>Import a phone ZIP, add camera files, or change the filters.</p></div>`}
 ${selection.size?html`<div class="batch-dock"><b>${selection.size} ${tr('selected')}</b>${filter==='trash'?button('Restore selected','restore-assets','','primary')+button('Delete selected permanently','purge-images','','danger'):html`<select id="batch-stop" aria-label="Assign selected to stop"><option value="">Choose stop…</option><option value="__none">Unassigned</option>${stops.map(s=>html`<option value="${e(s.id)}">${e(s.code+' · '+s.name)}</option>`).join('')}</select>${button('Assign','batch-assign')}<select id="batch-role" aria-label="Role for selected images">${roles.map(r=>html`<option value="${r}">${tr(r)}</option>`).join('')}</select>${button('Set role','batch-role')}${button('Move to Trash','trash-assets','','danger')}`}</div>`:''}
 </section>${review?html`<aside class="scene-inspector"><div class="row between"><h2>Scene context</h2>${button('Close','close-review','','quiet')}</div><h3>${e(review.fileName)}</h3>${review.blobId&&urls.has(review.blobId)?html`<img src="${urls.get(review.blobId)}" alt="${e(review.fileName)}">`:html`<p>Preview unavailable</p>`}<p>${e(review.camera||tr('Phone reference'))} · ${e(tr(review.role||'unclassified'))}</p><p>${e(review.captureWall||'')}</p>${scene?html`<h3>${e(scene.code+' · '+scene.name)}</h3>${vibe?.blobId&&urls.has(vibe.blobId)?html`<figure><img src="${urls.get(vibe.blobId)}" alt="${tr('Vibe reference')}"><figcaption>Phone vibe reference</figcaption></figure>`:''}<p>${e(localTime(scene.startedAt,scene.timezone))}</p><p>${scene.location?e(scene.location.lat.toFixed(5)+', '+scene.location.lng.toFixed(5)):tr('Location not recorded')}</p><p>${light?e(light.value)+' '+(light.method.endsWith('lux')?'lux':'EV100')+' · '+e(light.instrument):tr('No measurements yet. Missing readings stay empty.')}</p>${scene.weather?html`<p>${tr('Weather estimate')}: ${e(scene.weather.temperatureC??'—')} °C · ${tr('Cloud')} ${e(scene.weather.cloudCover??'—')}%<br><small>Open-Meteo · ${e(localTime(scene.weather.validAt,scene.weather.timezone))}</small></p>`:''}<p>${e(scene.notes)}</p>${button('Open stop','open',scene.id)}`:html`<p>Assign this file to a stop to see its field data.</p>`}${review.warnings?.length?html`<details><summary>Import details</summary>${review.warnings.map(w=>html`<p>${e(tr(w))}</p>`).join('')}</details>`:''}${button('Assign / describe','asset',review.id)}${review.blobId?button('Color sample','color',review.id,'quiet'):''}</aside>`:''}</div>`;
}
